# Generated by Django 3.2.25 on 2025-04-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250424_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaisettings',
            name='token_limit',
        ),
    ]
